# EGO POSE ESTIMATION PARAMETERS #

MM_TOP_LEFT_X_PXL = 55
MM_TOP_LEFT_Y_PXL = 55
MM_WIDTH_PXL = 230
MM_HEIGHT_PXL = 230

EPE_DBG = True

MM_TO_REF_SCALE_RATIO = 1.361712

FLANN_NUM_CHECKS = 50
FLANN_NUM_TREES = 5

MATCHING_MAX_RATIO = 0.3

# KALMAN FILTER PARAMETERS #
KF_TIME_STEP = 1
KF_X_ACCEL = 0
KF_Y_ACCEL = 0
KF_PROC_NOISE = 1
KF_X_STD_MEAS = 5
KF_Y_STD_MEAS = 5

KF_NEW_MEAS_MAX_DIST = 150

# GENERAL #
REF_MAP_PATH = 'data/map/olymp_map.png'
VID_PATH = 'data/vids/wraith 4k.mp4'
